### Data Analysis Intro

In [10]:
!pip install numpy
!pip install pandas

In [69]:
import numpy as np
v = np.array([[1,2,3,4],[5,6,7,8]])
print(v)
print(type(v))
print(v.shape)
v.reshape(8,1)
print(v.ndim)
print(f"{v.size} ** {v.dtype} ** {v.itemsize}")
print(np.zeros((2,3)))
print()
print(np.ones((2,3)))
print()
print(np.eye(3))
print(np.random.rand(2,3)) # rand and randn
print(np.random.randint(1,100,10))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
2
8 ** int64 ** 8
[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.56520251 0.03902229 0.89743545]
 [0.7143117  0.32003061 0.52374542]]
[29 26 21 86 29 23 70 52 48 47]


In [73]:
np.info(np.random.randint)

 randint(low, high=None, size=None, dtype=<class 'int'>)

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values

In [102]:
print(v[:,2])
print(v[v > 3])
print(v[0,:])
print(np.where(v>7))
print(np.take(v,[1,3]))
print(np.percentile(v,75))

[3 7]
[4 5 6 7 8]
[1 2 3 4]
(array([1]), array([3]))
[2 4]
6.25


In [114]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([3,4,5,67,90])
print(f"Addition : {np.add(a1,a2)}") # must size same
print(f"Substraction  : {np.subtract(a1,a2)}")
print(f"Variance of a1 : {np.var(a1)} and Variance of a2 : {np.var(a2)}")
print(f"Co-Variance of a1 : {np.cov(a1)} and Co-Variance of a2 : {np.cov(a2)}")
print(np.sqrt(a1[::1]))
print("Standard Deviation : ",np.std(v))

Addition : [ 4  6  8 71 95]
Substraction  : [ -2  -2  -2 -63 -85]
Variance of a1 : 2.0 and Variance of a2 : 1385.3600000000001
Co-Variance of a1 : 2.5 and Co-Variance of a2 : 1731.7000000000003
[1.         1.41421356 1.73205081 2.         2.23606798]
Standard Deviation :  2.29128784747792
