### Data Analysis Intro

In [1]:
# !pip install numpy
# !pip install pandas

In [2]:
import numpy as np
v = np.array([[1,2,3,4],[5,6,7,8]])
print(v)
print(type(v))
print(v.shape)
v.reshape(8,1)
print(v.ndim)
print(f"{v.size} ** {v.dtype} ** {v.itemsize}")
print(np.zeros((2,3)))
print()
print(np.ones((2,3)))
print()
print(np.eye(3))
print(np.random.rand(2,3)) # rand and randn
print(np.random.randint(1,100,10))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
2
8 ** int32 ** 4
[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.29318429 0.97720818 0.34735348]
 [0.37422199 0.66015902 0.9676366 ]]
[38 66 76 72 29 23 84 47 97  1]


In [3]:
np.info(np.random.randint)

randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.randint`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  I

In [4]:
print(v[:,2])
print(v[v > 3])
print(v[0,:])
print(np.where(v>7))
print(np.take(v,[1,3]))
print(np.percentile(v,75))

[3 7]
[4 5 6 7 8]
[1 2 3 4]
(array([1], dtype=int64), array([3], dtype=int64))
[2 4]
6.25


In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([3,4,5,67,90])
print(f"Addition : {np.add(a1,a2)}") # must size same
print(f"Substraction  : {np.subtract(a1,a2)}")
print(f"Variance of a1 : {np.var(a1)} and Variance of a2 : {np.var(a2)}")
print(f"Co-Variance of a1 : {np.cov(a1)} and Co-Variance of a2 : {np.cov(a2)}")
print(np.sqrt(a1[::1]))
print("Standard Deviation : ",np.std(v))

Addition : [ 4  6  8 71 95]
Substraction  : [ -2  -2  -2 -63 -85]
Variance of a1 : 2.0 and Variance of a2 : 1385.3600000000001
Co-Variance of a1 : 2.5 and Co-Variance of a2 : 1731.7000000000003
[1.         1.41421356 1.73205081 2.         2.23606798]
Standard Deviation :  2.29128784747792


In [6]:
import pandas as pd
data = [1,2,3,4,5,6]
series = pd.Series(data)
print(series)
##Dict Passing
data = {'a' : 1,'b' : 2,'c' : 3,'d' : 4}
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [7]:
data = pd.read_csv('sales_data.csv')
print(data.head(5))
data = [
    {'Name' : 'Vedant','Age' : 23,'country' : 'India','Job' : 'No'},
    {'Name' : 'Ved','Age' : 30,'country' : 'India','Job' : 'No'},
    {'Name' : 'ant','Age' : 29,'country' : 'India','Job' : 'No'},
    {'Name' : 'nt','Age' : 32,'country' : 'India','Job' : 'No','Peding' : 'Yes'},
]
df = pd.DataFrame(data)
print(df)


   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal  
     Name  Age country Job Peding
0  Vedant   23   India  No    NaN
1     Ved   30   India  No    NaN
2     ant

In [8]:
a = [1, 2, 3]
b = [1, 2, 3]
result = [x+y for x, y in zip(a,b)]
print(result)

a = np.array([1,2,3])
b = np.array([1,2,3])
result = a + b
print(result)

print(np.full((2,2), 7))
print(np.arange(0, 10, 2),'\n',         # like range()
np.linspace(0, 1, 5))

[2, 4, 6]
[2 4 6]
[[7 7]
 [7 7]]
[0 2 4 6 8] 
 [0.   0.25 0.5  0.75 1.  ]


In [14]:
arr = np.arange(1, 7)     # [1 2 3 4 5 6]
mat = arr.reshape((2, 3)) # 2 rows, 3 columns
print(mat)
print(arr.reshape((3, 2)))
print(arr.flatten())   # convert 2D → 1D
print(arr.ravel())     # memory-efficient flatten
print(arr.T)           # transpose
print("Done Compilling!!")

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
Done Compilling!!


In [15]:
print("Compilling New Packages ?? ")

Compilling New Packages ?? 
